### ISSUE TITLE
S. 30 / "Die harmonische Reihe"

### ISSUE THREAD

**Issue by mauriziopiu** [raw-bacon/ana1-notes#16]
Bei der Ungleichung nach "Allgemeiner gilt:", steht auf der rechten Seite der Ungleichung "**2n** * ( 1 / 2n) = 1 / 2". Dort sollte (wahrscheinlich) "**n** * ( 1 / 2n) = 1 / 2" stehen.

<img width="524" alt="issue1" src="https://user-images.githubusercontent.com/71320041/104580859-15f19300-565e-11eb-8f0d-a21b6941a9b9.png">

**Comment by lryffel** [comment]
Genau, danke!
